### ISSUE TITLE
[🐛] Invalid hook call. Hooks can only be called inside of the body of a function component 

### ISSUE THREAD

**Issue by devth** [snyk-tech-services/backstage-plugin-snyk#82]
- `node -v`: v16.13.2
- `npm -v`: 8.3.2
- OS: macOS

### Expected behavior

Expected Snyk components to render without errors.

### Actual behavior

Following instructions on the [README](https://github.com/snyk-tech-services/backstage-plugin-snyk), I encounter hook errors any time I try rendering any of the Snyk components

```
Error
Error

Message
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

Stack Trace
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (webpack-internal:///../../node_modules/backstage-plugin-snyk/node_modules/react/cjs/react.development.js:1465:13)
    at useContext (webpack-internal:///../../node_modules/backstage-plugin-snyk/node_modules/react/cjs/react.development.js:1473:20)
    at useAnalyticsContext (webpack-internal:///../../node_modules/backstage-plugin-snyk/node_modules/@backstage/core-plugin-api/dist/index.esm.js:57:71)
    at AnalyticsContext (webpack-internal:///../../node_modules/backstage-plugin-snyk/node_modules/@backstage/core-plugin-api/dist/index.esm.js:75:24)
    at renderWithHooks (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:14985:18)
    at mountIndeterminateComponent (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:17811:13)
    at beginWork (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:19049:16)
    at HTMLUnknownElement.callCallback (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:3994:16)
    at invokeGuardedCallback (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:4056:31)
```

### Screenshots

<img width="644" alt="image" src="https://user-images.githubusercontent.com/86107/155816949-f3e280e3-3e28-4e0f-a885-34f247da1460.png">

### Repro

Code like this:

```tsx
import { Grid } from '@material-ui/core';
import {
  EntityHasSubcomponentsCard,
  EntityLinksCard,
} from '@backstage/plugin-catalog';
import React from 'react';
import { EntityAboutCard } from './EntityAboutCard';
import { EntityWarningContent } from './EntityWarningContent';
import { useEntity } from '@backstage/plugin-catalog-react';
import { EntityCatalogGraphCard } from '@backstage/plugin-catalog-graph';
import { EntitySonarQubeCard } from '@backstage/plugin-sonarqube';
import { SnykOverview } from 'backstage-plugin-snyk';

export const entityOverviewContent = (
  <Grid container spacing={3} alignItems="stretch">
    <EntityWarningContent />
    <Grid item md={6} xs={12}>
      <EntityAboutCard />
    </Grid>
    <Grid item md={6} xs={12}>
      <EntityCatalogGraphCard variant="gridItem" height={250} />
    </Grid>
    <Grid item xs={12}>
      <EntityHasSubcomponentsCard variant="gridItem" />
    </Grid>
    <Grid item md={6} xs={12}>
      <EntitySonarQubeCard variant="gridItem" />
    </Grid>
    <Grid item md={6} xs={12}>
      <SnykOverview />
    </Grid>
  </Grid>
);

```

**Comment by devth** [comment]
I think this is due to `1. You might have mismatching versions of React and the renderer (such as React DOM)`

I'm on 17 and the snyk plugin specifies 16.

```
yarn why v1.22.17
[1/4] Why do we have the module "react"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
info 
=> Found "react@17.0.2"
info Has been hoisted to "react"
info Reasons this module exists
   - "workspace-aggregator-c93cbe48-b4e9-4f9a-b65c-acdde9c858eb" depends on it
   - Hoisted from "_project_#app#react"
   - Hoisted from "_project_#log4brains#@log4brains#web#react"
info Disk size without dependencies: "356KB"
info Disk size with unique dependencies: "404KB"
info Disk size with transitive dependencies: "432KB"
info Number of shared dependencies: 3
info 
=> Found "backstage-plugin-snyk#react@16.14.0"
info Reasons this module exists
   - "_project_#app#backstage-plugin-snyk#@backstage#core-plugin-api" depends on it
   - Hoisted from "_project_#app#backstage-plugin-snyk#@backstage#core-plugin-api#react"
info Disk size without dependencies: "332KB"
info Disk size with unique dependencies: "572KB"
info Disk size with transitive dependencies: "652KB"
info Number of shared dependencies: 5
Done in 2.25s.
```

Searched backstage discord a bit, and found a reference to https://github.com/backstage/backstage/blob/master/packages/create-app/CHANGELOG.md#0414, which says:

> Since we have recently moved over all react and react-dom dependencies to peerDependencies of all packages, and included React 17 in the version range, this should be all you need to do

Should this plugin also make react/react-dom peerDependencies?

**Comment by devth** [comment]
Digging a bit further, it's actually coming from an outdated `@backstage/core-plugin-api` specified [here](https://github.com/snyk-tech-services/backstage-plugin-snyk/blob/v1.2.2/package.json#L18):

```
backstage-plugin-snyk@^1.2.2:
  version "1.2.2"
  resolved "https://registry.yarnpkg.com/backstage-plugin-snyk/-/backstage-plugin-snyk-1.2.2.tgz#296b020bbe05d68cde452f05d3400dbce296fc3f"
  integrity sha512-LhRz8sS5oUJRqKVmDEnIc18VjVAW4tSoYjLZ7RfbEZARgzCRQtgNNoYy0Wvr9dIQmiZR+39GhirXyaAdB43tyA==
  dependencies:
    "@backstage/catalog-model" "0.9.9"
    "@backstage/core-components" "^0.8.0"
    "@backstage/core-plugin-api" "^0.1.9"
```

**Comment by devth** [comment]
Fixed by https://github.com/snyk-tech-services/backstage-plugin-snyk/pull/85
